//Clase generada con el generador php de clases para Xcode de Gino Lluen
    //Con cariño para Jasoft - 2013
	//Primera Version - 2013
    
    #import <Foundation/Foundation.h>
    #import "Conexion.h"
    
    @interface perupez_hrm_employee : NSObject{NSString* pkEmployee;
            NSString* fkPerson;
            NSString* fkCompany;
            NSString* fkEstablishment;
            NSString* fkCompanyPosition;
            NSString* fkDependency;
            NSString* fkEmployeeType;
            NSString* fkLaboralSystem;
            NSString* fkOccupation;
            NSString* fkPensionType;
            NSString* fkPensionSystem;
            NSString* fkLaborCondition;
            NSString* fkPayPeriod;
            NSString* fkEmployeeSituation;
            NSString* fkEmployeeSpecialSituation;
            NSString* fkPaymentType;
            NSString* fkOccupationCategory;
            NSString* fkOccupationalGroup;
            NSString* fkAgreementAvoidDoubleTaxation;
            NSString* fkHealthInsurance;
            NSString* fkPayrollType;
            NSString* fkMeasureUnit;
            NSString* fkMoneyType;
            NSString* employeeCode;
            NSString* isHandicapped;
            NSString* cuspp;
            NSString* hasAlternateRegimen;
            NSString* hasMaxDay;
            NSString* hasNightTime;
            NSString* hasLaborUnion;
            NSString* startingSalary;
            NSString* fifthCategoryExemptIncome;
            NSString* essaludMasVida;
            NSString* pensionSystemAffiliationDate;
            NSString* isAffectedToOvertime;
            NSString* isPieceWorker;
            NSString* acceptExtraBonifications;
            NSString* isServiceProvider;
            NSString* isDomiciled;
            NSString* registrationDate;
            NSString* statusRegister;
            }
    - (int) set_pkEmployee: (NSString *)nuevo_valor;
        - (NSString*) get_pkEmployee;
        - (int) set_fkPerson: (NSString *)nuevo_valor;
        - (NSString*) get_fkPerson;
        - (int) set_fkCompany: (NSString *)nuevo_valor;
        - (NSString*) get_fkCompany;
        - (int) set_fkEstablishment: (NSString *)nuevo_valor;
        - (NSString*) get_fkEstablishment;
        - (int) set_fkCompanyPosition: (NSString *)nuevo_valor;
        - (NSString*) get_fkCompanyPosition;
        - (int) set_fkDependency: (NSString *)nuevo_valor;
        - (NSString*) get_fkDependency;
        - (int) set_fkEmployeeType: (NSString *)nuevo_valor;
        - (NSString*) get_fkEmployeeType;
        - (int) set_fkLaboralSystem: (NSString *)nuevo_valor;
        - (NSString*) get_fkLaboralSystem;
        - (int) set_fkOccupation: (NSString *)nuevo_valor;
        - (NSString*) get_fkOccupation;
        - (int) set_fkPensionType: (NSString *)nuevo_valor;
        - (NSString*) get_fkPensionType;
        - (int) set_fkPensionSystem: (NSString *)nuevo_valor;
        - (NSString*) get_fkPensionSystem;
        - (int) set_fkLaborCondition: (NSString *)nuevo_valor;
        - (NSString*) get_fkLaborCondition;
        - (int) set_fkPayPeriod: (NSString *)nuevo_valor;
        - (NSString*) get_fkPayPeriod;
        - (int) set_fkEmployeeSituation: (NSString *)nuevo_valor;
        - (NSString*) get_fkEmployeeSituation;
        - (int) set_fkEmployeeSpecialSituation: (NSString *)nuevo_valor;
        - (NSString*) get_fkEmployeeSpecialSituation;
        - (int) set_fkPaymentType: (NSString *)nuevo_valor;
        - (NSString*) get_fkPaymentType;
        - (int) set_fkOccupationCategory: (NSString *)nuevo_valor;
        - (NSString*) get_fkOccupationCategory;
        - (int) set_fkOccupationalGroup: (NSString *)nuevo_valor;
        - (NSString*) get_fkOccupationalGroup;
        - (int) set_fkAgreementAvoidDoubleTaxation: (NSString *)nuevo_valor;
        - (NSString*) get_fkAgreementAvoidDoubleTaxation;
        - (int) set_fkHealthInsurance: (NSString *)nuevo_valor;
        - (NSString*) get_fkHealthInsurance;
        - (int) set_fkPayrollType: (NSString *)nuevo_valor;
        - (NSString*) get_fkPayrollType;
        - (int) set_fkMeasureUnit: (NSString *)nuevo_valor;
        - (NSString*) get_fkMeasureUnit;
        - (int) set_fkMoneyType: (NSString *)nuevo_valor;
        - (NSString*) get_fkMoneyType;
        - (int) set_employeeCode: (NSString *)nuevo_valor;
        - (NSString*) get_employeeCode;
        - (int) set_isHandicapped: (NSString *)nuevo_valor;
        - (NSString*) get_isHandicapped;
        - (int) set_cuspp: (NSString *)nuevo_valor;
        - (NSString*) get_cuspp;
        - (int) set_hasAlternateRegimen: (NSString *)nuevo_valor;
        - (NSString*) get_hasAlternateRegimen;
        - (int) set_hasMaxDay: (NSString *)nuevo_valor;
        - (NSString*) get_hasMaxDay;
        - (int) set_hasNightTime: (NSString *)nuevo_valor;
        - (NSString*) get_hasNightTime;
        - (int) set_hasLaborUnion: (NSString *)nuevo_valor;
        - (NSString*) get_hasLaborUnion;
        - (int) set_startingSalary: (NSString *)nuevo_valor;
        - (NSString*) get_startingSalary;
        - (int) set_fifthCategoryExemptIncome: (NSString *)nuevo_valor;
        - (NSString*) get_fifthCategoryExemptIncome;
        - (int) set_essaludMasVida: (NSString *)nuevo_valor;
        - (NSString*) get_essaludMasVida;
        - (int) set_pensionSystemAffiliationDate: (NSString *)nuevo_valor;
        - (NSString*) get_pensionSystemAffiliationDate;
        - (int) set_isAffectedToOvertime: (NSString *)nuevo_valor;
        - (NSString*) get_isAffectedToOvertime;
        - (int) set_isPieceWorker: (NSString *)nuevo_valor;
        - (NSString*) get_isPieceWorker;
        - (int) set_acceptExtraBonifications: (NSString *)nuevo_valor;
        - (NSString*) get_acceptExtraBonifications;
        - (int) set_isServiceProvider: (NSString *)nuevo_valor;
        - (NSString*) get_isServiceProvider;
        - (int) set_isDomiciled: (NSString *)nuevo_valor;
        - (NSString*) get_isDomiciled;
        - (int) set_registrationDate: (NSString *)nuevo_valor;
        - (NSString*) get_registrationDate;
        - (int) set_statusRegister: (NSString *)nuevo_valor;
        - (NSString*) get_statusRegister;
        
    - (int) insertDB;
    - (int) modDB;
    - (int) delDb;
    - (NSMutableArray*) allDB;
    - (NSMutableArray*) getDB;
    - (NSMutableArray*) listParameters: (NSString *)list;
    
    @end